const fs=require('fs');
let html=fs.readFileSync('index.html','utf8');
const m=html.match(/<script>([\s\S]*)<\/script>/);
let code=m[1];
const store={};
global.document={getElementById:(id)=>({set innerHTML(v){store[id]=v;}, get innerHTML(){return store[id]||'';}}),querySelectorAll:()=>[]};
global.window={scrollTo:()=>{}};
code=code.replace(/\nrender\(\);\s*$/,'\n');
const fn=new Function('document','window',code+'\nreturn {SC:SC, screen:screen, logDialog:logDialog};');
const api=fn(global.document,global.window);
const l1=api.SC.filter(s=>s.id==='l1')[0];
const scr=api.screen(l1);
console.log('LEN',scr.length);
const i=scr.indexOf('sr-only');
console.log('SR SEGMENT:',JSON.stringify(scr.slice(i-20,i+520)));
const w1=api.SC.filter(s=>s.id==='w1')[0];
const w=api.screen(w1);
console.log('W1 LEN',w.length);
console.log('W1 HEAD',JSON.stringify(w.slice(0,400)));
